### ISSUE TITLE
Resource Page Idea: A list of services or companies that provide free, "fair-use" images and gifs

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1128]
As a producer of content for the web and social media, it would be great if we had a resource that listed out the services or companies that provide free, "fair-use" images and gifs for public use. 

Putting together shared resource is a step toward making finding better images to use,  easier for people in government.

### What is needed to make this happen

We need people in the community to help gather a list of all the services or companies that provide free, "fair-use" images for public use.

Here is our first submission

- The National Archives GIPHY channel: https://giphy.com/usnationalarchives  (from Darren Cole at the National Archives)

We will publish this list as a resource page on digital.gov.

**Comment by thomas-oneill** [comment]
We have an internal list of DOE Flickr and Instagram accounts.  I feel most should be listed at U.S. Digital Registry.  

Below is another list that I created a few years ago:
* http://www.archives.gov/research/search/ Online Public Access Search - National Archives
* http://loc.gov/pictures/ Prints and Photographs Online Catalog - Library of Congress
* http://www.dvidshub.net/ Defense Video &amp; Imagery Distribution System (DVIDS) - Department of Defense
* https://search.usa.gov/search/images?affiliate=usagov&query=l USA.gov Images Search
* http://www.peacecorps.gov/media/digital-library/ Peace Corp Media Library
* https://openi.nlm.nih.gov/index.php Open-i Open Access Biomedical Image Search Engine - NIH 
* http://phil.cdc.gov/phil/home.asp Public Health Image Library (PHIL) - Centers for Disease Control and Prevention 
* Department of State http://www.state.gov/r/pa/ei/pix/index.htm Photo Gallery
* USDA http://www.ers.usda.gov/newsroom/photos-images.aspx photos and images
* NOAA http://www.photolib.noaa.gov/ photo library
* NIST http://patapsco.nist.gov/imagegallery/ image gallery
https://www.ed.gov/category/resource-type/images
* Department of Interior|U.S Department of Interior photos - https://www.doi.gov/photos
* https://www.cia.gov/library/ CIA library
* Department of Justice http://www.justice.gov/opa/galleries photo galleries
* House of Representatives http://history.house.gov/Collection/Search?Classification=Photographs photographs
* Senate http://www.senate.gov/art/art_hist_home.htm art history images
* Supreme Court http://www.supremecourt.gov/about/historicCollections.aspx historic collections
* https://www.whitehouse.gov/photos-and-video/photogallery/december-2015-photo-day White House photos and videos

**Comment by thomas-oneill** [comment]
Another list, that should be checked, is below:
* http://www.freeimages.com/ - A website providing free-to use stock photography and illustrations, its name being a reduced version of "stock exchange" (meaning the exchange of stock photography, and a play on the term stock exchange). 
* https://unsplash.com/ - Unsplash is a great source for free high-resolution photos. It offers a mixture of urban shots and rural landscapes, as well as object close-ups. You can find almost anything here. "Made With Unsplash" is a page where users can post projects in which they used Unsplash photos so visitors can see the photography in action. Unsplash updates every 10 days with 10 new images. It has a Creative Commons license, so you can copy, modify and distribute the work—even for commercial purposes—without asking for permission. 
* http://albumarium.com/ - Albumarium is another great resource for high-resolution stock images. It has close-ups of animals, nature and people in modern and vintage styles. Instead of a Tumblr-like user experience, you search by album to see a collection of images for each subject. Albumarium has about 30 albums, and with titles including Converse, Babies, Elephants and Redheads, it's clear it has a fun range of topics. 
* http://startupstockphotos.com/ Start-up Stock Photos features many images of people working in coffee shops with the requisite mobile phones and laptops. It's perfect for websites that regularly cover freelancers or startups. 
* http://littlevisuals.co/ - Like Unsplash, Little Visuals is a source of high-resolution images in the public domain and under a Creative Commons license. Little Visuals emails you a zip folder of seven images every seven days. Unsplash's images a bit more intriguing and practical; Little Visuals' are more abstract and conceptual. 
* http://www.lifeofpix.com/ - Leeroy, an advertising agency in Montreal, created this website. All images are free for personal or commercial use. With multiple themes throughout each page, you'll find a lot of great nature close-ups, including heads of lettuce, bees collecting pollen and even a polar bear under water. These images are useful for backgrounds and patterns. 
* https://www.vecteezy.com/ Vecteezy has a decent selection of both raster and vector images that should be cost-free and royalty-free

**Comment by thomas-oneill** [comment]
One of the best sources I have found is https://commons.wikimedia.org/wiki/Main_Page.

**Comment by thomas-oneill** [comment]
Don't forget USA.gov image search (https://search.usa.gov/search/images?affiliate=usagov&query=).

**Comment by ToniBonittoGSA** [comment]
Hi @thomas-oneill 

Wow, thanks so much! We'll def. be going through these

As for the U.S. Digital Registry, have you/your social media manager(s) added DOE's Flickr and IG accts to https://usdigitalregistry.digitalgov.gov/ ?

**Comment by jeremyzilar** [comment]
This is wonderful @thomas-oneill and more than a modest start to the page 🎉 
We will start putting it together

**Comment by afeijoo** [comment]
According to USAgov's page on [U.S. Government Works](https://www.usa.gov/government-works), not all images that appear on .gov websites are considered to be government works. Some may be protected intellectual property not owned by the government but used by permission of the rights holder.

**Comment by jeremyzilar** [comment]
@thomas-oneill — the DOE Flickr accounts that you mention, are those images also free and fair use?

**Comment by jeremyzilar** [comment]
We have a draft pulled together, and are in the process of getting some eyes on it internally.
We'll share out a working draft as soon as we have it @thomas-oneill

**Comment by jeremyzilar** [comment]
We are currently working with our legal team at the GSA on the language needed to frame out these resources on our page. Will update soon!

**Comment by bwalls** [comment]
NASA has a site set up for search and download of full-resolution imagery (video, still, and audio files) at https://images.nasa.gov.

**Comment by saracope** [comment]
@jeremyzilar Any update on the response from legal?
