### ISSUE TITLE
Linked files are "missing" -- XML loads instead of document/audio file

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#184]
When a user clicks on links for files (.txt, .pdf, .mp3, .doc, etc.), an XML file/page loads instead of the actual document/audio files.

Examples: 
https://www.digitalgov.gov/resources/open-opportunities-task-creator-toolkit/ 
https://www.digitalgov.gov/2014/03/04/creating-awesome-web-analytics-reports-and-presentations/ 
https://www.digitalgov.gov/resources/negotiated-terms-of-service-agreements/

**Comment by thisisdano** [comment]
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9FAE26E1FDA3BF39</RequestId>
<HostId>
BmCQ4K/yVGfKbvrHZ8FBZJPIS6S056+xwBEzGIV0+tvtyBhmca+mUhVh6dODp4E69X2aoknKXJ0=
</HostId>
</Error>
```

This is the error, which is probably caused by incorrect permissions in our S3 bucket. I'll check

**Comment by thisisdano** [comment]
Freaking criminal that you can't search inside an S3 bucket

**Comment by thisisdano** [comment]
OK, looks like the isn't a permissions issue, rather, the link is wrong

What we have:
`https://s3.amazonaws.com/digitalgov/legacy-img/2015/04/Open-Opps-Marketing-Email-Template-for-CoPs.docx`

What we need:
`https://s3.amazonaws.com/digitalgov/_legacy-img/2015/04/Open-Opps-Marketing-Email-Template-for-CoPs.docx`

Path should be `_legacy-img` rather than `legacy-img`.

**Comment by thisisdano** [comment]
Fixed ~750 links, readying a hotfix.

**Comment by thisisdano** [comment]
Here's the fix: https://github.com/GSA/digitalgov.gov/pull/191

**Comment by jeremyzilar** [comment]
This has been completed.
