### ISSUE TITLE
[Content Cleanup]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1878]
### URL / Link to page
https://digital.gov/

### What seems to be the problem (1 sentence)
There are two (2) instances of USWDS Monthly Call and the graphic on the right side appears differently in each block. 

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by jeremyzilar** [comment]
Yes, one is the January monthly call, the other is the Dec monthly call.
I can 
- get an image for the dec call and add it to youtube so that its more clear from the image what month it is for.
- figure out a better construction for the titles of these events so that it is more clear what month it was created it

**Comment by saracope** [comment]
Looks like this was updated/resolved. Can close? @jeremyzilar

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
