### ISSUE TITLE
Create a new resources page template

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#206]
### v1
![image](https://user-images.githubusercontent.com/395641/32568781-47d216ee-c48d-11e7-991d-bb1d3cdad976.png)

### v2 (updated)
![image](https://user-images.githubusercontent.com/395641/32571481-8487f6be-c495-11e7-90fb-151f1b9468e3.png)

**Comment by thisisdano** [comment]
I might encourage sticking to one level of navigation in the sidenav (and not including a sublevel) and considering displaying in-page anchor navigation on the right instead of the left.

Flat-hierarchy sidenav has a few benefits:

- less complicated
- shorter, more easily made sticky
- encourages less lengthy pages
- avoids a complication with accordion navs where the nav item has to play both the role of a link (linking to the header) and an action trigger (opening the accordion)

**Comment by thisisdano** [comment]
Right-side anchor nav provides a smoother reading experience (establishing the left margin as the left edge of the text block) and provides distinction from "classic" sidenav, which tends to be _inter_page rather than _intra_page.

**Comment by jeremyzilar** [comment]
Thanks @thisisdano — I updated the wireframe to include the nav on the right, and added a single-level navigation. What are your thoughts on grouping nav items?

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
