### ISSUE TITLE
[Suggestion] Pull relevant USAJobs to the CoP or Topic pages

### ISSUE THREAD

**Issue by RhettSkelton** [GSA/digitalgov.gov#2727]
### URL / Link to page
USAJobs Developer Site: https://developer.usajobs.gov/

### Tell us how we can make this page better
Sharing jobs seems to drive a lot of discussion in the LISTSERV and Open Opportunities is often a highly clicked link in the newsletter. We should consider creating searches for each CoP, if not topic, and using the USAJobs API to pull in relevant jobs to drive more traffic to the website.

**Comment by afeijoo** [comment]
Search.gov has a jobs search feature, so be sure to connect with https://github.com/dawnpm.

**Comment by dawnpm** [comment]
We could implement the jobs module for digitalgov's search, but it would be best implemented as a separate search configuration, so that we could retain the scoping suggested in Rhett's original post and yet not spam all searchers on digitalgov with jobs from across government. It would probably take some fancy footwork to append the topic keywords to the query depending on which community or subject area the job seeker is interested in, but it's definitely doable.
