### ISSUE TITLE
Display error on H2 titles: tag, category pages

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#290]
There is an odd line break on Post titles when displayed on all **tag** and **category** Pages

**Examples**:
https://www.digitalgov.gov/tag/usds/ 
https://www.digitalgov.gov/categories/api/ 

but there's no line break or `<br />` in the code; example: 

`<h2 class="post-title"><a href="/2017/06/07/the-data-briefing-design-driven-enterprise-architecture-creating-the-new-federal-government-agency/" rel="bookmark" title="The Data Briefing: Design-Driven Enterprise Architecture Creating the New Federal Government Agency">The Data Briefing: Design-Driven Enterprise Architecture Creating the New Federal Government Agency</a></h2>`

<img width="1280" alt="screen shot 2017-12-26 at 10 00 14 am" src="https://user-images.githubusercontent.com/19961574/34359191-d83c969e-ea23-11e7-8944-f1d06cbbf41f.png">

---
Just FYI -- 

1) The flow of the Post title is fine on the individual Post pages. Examples from above tag and category:

  * https://www.digitalgov.gov/2017/08/28/government-launches-login-gov-to-simplify-access-to-public-services/ 
  * https://www.digitalgov.gov/2017/06/07/the-data-briefing-design-driven-enterprise-architecture-creating-the-new-federal-government-agency/ 

Title code from 2nd bullet is: 

`<h1 class="post-title single"><a href="/2017/06/07/the-data-briefing-design-driven-enterprise-architecture-creating-the-new-federal-government-agency/" rel="bookmark" title="The Data Briefing: Design-Driven Enterprise Architecture Creating the New Federal Government Agency">The Data Briefing: Design-Driven Enterprise Architecture Creating the New Federal Government Agency</a></h1>`

_Only difference is 'single' attribute in the H1_ 

2) The flow of long H2s within posts is ok, too 

https://www.digitalgov.gov/2016/09/19/how-do-you-redesign-a-dinosaur-redesigning-an-intranet-site-the-beginning-stages/

**Comment by decrisdw** [comment]
Wasn't sure if you figured this one out yet but I noticed that it looks like the line break is happening because of the div below: 

(located on the [https://www.digitalgov.gov/tag/usds/](https://www.digitalgov.gov/tag/usds/) page)

`<div class="post-feature-image"><a href="/2017/08/28/government-launches-login-gov-to-simplify-access-to-public-services/" rel="bookmark" title="Permanent link to Government Launches Login.Gov to Simplify Access to Public Services"><img class="thumbnail large" src="" alt="" title=""></a></div>`

If you delete it or change its css to 'display:none', it fixes the page break.

**Comment by jeremyzilar** [comment]
Thank you @decrisdw for the 👀 on that 🎉 
We will get this fix in this week.
