### ISSUE TITLE
Bug: Event Showing in Past and Present Sections of DG.gov/events

### ISSUE THREAD

**Issue by RhettSkelton** [GSA/digitalgov.gov#3428]
**Describe the bug**
The USPS CX event is appearing as a future and past event on the Digital.gov/events page.

**Steps to Reproduce**
1. Go to 'digital.gov/events'
2. Scroll down to 'see the USPS event in the upcoming list, then again in the Past Event list'
3. It should only appear in Past Events since this event happened last week.

**Screenshots**
<img width="993" alt="Screen Shot 2020-11-16 at 1 12 30 PM" src="https://user-images.githubusercontent.com/12884066/99291776-51164800-280e-11eb-9721-38c07f7e57df.png">

**Comment by RhettSkelton** [comment]
filename: 2020-10-20-customer-experience-continuous-improvement-the-usps-digital-approach

**Comment by ToniBonittoGSA** [comment]
Issue resolved itself when I merged an update
 -- though.. it was a weird, new issue that this event even appeared in 2 spots on the page.
Closing.

**Comment by saracope** [comment]
Going to reopen this as a general issue to review and see if it is recreatable.

**Comment by Krithisree** [comment]
The reason that some of the recently expired events showing on the Events list seems to be related to Caching. This doesn't happen in local as the Hugo server refreshes every time we build. The production or staging servers do not have this issue when restarted which means the cache is cleared. Online forums indicate that this is a known issue with Hugo. There are suggestions to restart Hugo server frequently or adding extra parameters to disable fast rendering to avoid caching. But this will impact performance slightly because the most frequently visited pages are not cached. Other suggestions include updating Hugo to a recent version which may clear this issue. Updating to the recent version might need more testing and see if any other features have conflicts/issues.
